CREATE DATABASE energy_data_vault;

\c energy_data_vault;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

--Измените пароль в данной строке на свой--
CREATE USER etl_user WITH PASSWORD 'your_password';

GRANT CONNECT ON DATABASE energy_data_vault TO etl_user;

GRANT USAGE, CREATE ON SCHEMA bronze TO etl_user;
GRANT USAGE, CREATE ON SCHEMA silver TO etl_user;
GRANT USAGE, CREATE ON SCHEMA gold TO etl_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA bronze GRANT ALL ON TABLES TO etl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT ALL ON TABLES TO etl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT ALL ON TABLES TO etl_user;